django-survey/django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

django-survey/django/conf/project_template/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

django-survey/survey/urls.py
from django.conf.urls import patterns, url
from survey.views import * 

urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^(?P<survey_id>\d+)/$', open_survey, name='open_survey'),
    url(r'^create_survey/$', create_survey, name='create_survey'),
    url(r'^delete_survey/(?P<survey_id>\d+)/$', delete_survey, name='delete_survey'),
    url(r'^edit_title/(?P<survey_id>\d+)/$', edit_title, name="edit_title"),
    url(r'^create_question/(?P<survey_id>\d+)/$', create_question, name='create_question'),
    url(r'^submit_survey/(?P<survey_id>\d+)/$', submit_survey, name='submit_survey'),
    url(r'^show_results/(?P<survey_id>\d+)/$', show_results, name='show_results'),
    url(r'show_image/(?P<survey_id>\d+)/(?P<question_id>\d+)/$', show_image, name='show_image'),
    url(r'^logout/$', logout, name='logout')
)

django-survey/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'django.views.generic.simple.redirect_to', {'url': '/survey/', }),
    url(r'^survey/', include('survey.urls', namespace="survey")),
)

django-survey/survey/models.py
from django.db import models
from datetime import datetime

class UserProfile(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length = 200)
    last_name = models.CharField(max_length = 200)
    employer = models.CharField(max_length = 200)
    photo = models.ImageField(upload_to = None, blank = True, null = True)

    def _unicode(self):
        return self.email

class Survey(models.Model):
    survey_title = models.CharField(max_length = 200, blank = False)
    date_created = models.DateTimeField(default = datetime.today())
    owner = models.ForeignKey(UserProfile)
    
    '''Determines if the current user is the Survey owner'''
    def is_survey_owner(self, current_user):
        return current_user == self.owner.email

    '''Delete this Survey, along with all Q&A associated w/ it.'''
    def delete(self):
        for question_bean in self.question_set.all():
            for response_bean in question_bean.response_set.all():
                response_bean.delete()
            question_bean.delete()
        super(Survey, self).delete()

    def contains_response(self, response_bean):
        for question_bean in self.question_set.all():
            if response_bean in question_bean.response_set.all():
                return True
        return False

    def _unicode_(self):
        return self.survey_title


class Question(models.Model):
    survey = models.ForeignKey(Survey)
    question_text = models.CharField(max_length = 200, blank = False)
    image_file = models.ImageField(upload_to = None, blank = True, null = True)

    def _unicode_(self):
        return self.question_text
        
    class Meta:
        order_with_respect_to = "survey"

        
class Response(models.Model):
    question = models.ForeignKey(Question)
    response_text = models.CharField(max_length = 200, blank = False)
    votes = models.IntegerField(default=0)
    position = models.IntegerField(default = 0)
    
    '''Increment the number of times that this response was chosen.'''
    def increment_votes(self):
        self.votes = self.votes + 1
        
    def _unicode_(self):
        return self.response_text;

django-survey/survey/forms.py
from django import forms
from django.forms import Form, ModelForm
from survey.models import *

class ProfileForm(ModelForm):
    '''Return whether a UserProfile exists for the given email'''
    def exists_profile(self, user_email):
        try:
            UserProfile.objects.get(email = user_email)
            return True
        except UserProfile.DoesNotExist:
            return False
        
    '''If there is no UserProfile for the given email, then create one.'''
    def create_profile(self, user_email):
        if self.exists_profile(user_email):
            return False
        
        user_bean = UserProfile()
        user_bean.email = user_email
        user_bean.save()
        return True
    
    class Meta:
        model = UserProfile
        fields = ['email']


class SurveyForm(ModelForm):
    survey_title = forms.CharField(max_length = 200, error_messages = {'required': 'Survey Title Required'})

    class Meta:
        model = Survey
        fields = ['survey_title']


class QuestionForm(ModelForm):
    question_text = forms.CharField(max_length = 200, error_messages = {'required' : 'Question Required'})
    image_file = forms.ImageField(required = False)
    
    class Meta:
        model = Question
        fields = ['question_text']
        

class ResponseForm(Form):
    # The user must submit at least 2 valid, complete response options
    # in order for the question and responses to be processed.
    def is_valid_response_list(self, response_list):
        num_valid_inputs = 0
        for value in response_list:
            if value.strip():
                num_valid_inputs = num_valid_inputs + 1
        if num_valid_inputs >= 2:
            return True
        return False
    
    # Save only the Response beans with non-empty response options.
    def save_response_list(self, question_bean, response_list):
        count = 0
        for value in response_list:
            if value.strip():
                response_bean = Response(response_text = value, question = question_bean)
                response_bean.position = count + 1
                count = count + 1
                response_bean.save()

django-survey/survey/views.py
import webapp2
from google.appengine.api import users
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from survey.models import *
from survey.forms import *
from mimetypes import guess_type

################Helper Methods - Handle repeated sections of code.####################
'''Create the request context for the home page.'''
def create_default_context():
    context = {}
    context['user_email'] = users.get_current_user().email()
    context['survey_list'] = Survey.objects.all().order_by('-date_created')
    return context

'''Create the request context for a specific survey's page.'''
def create_survey_context(survey_bean):
    context = {}
    context['survey'] = survey_bean
    return context


##################Actions - mapped to specific urls in urls.py########################
'''Display home (user profile) page.'''
def home(request):
    ProfileForm().create_profile(users.get_current_user().email())   
    return render(request, 'survey/home.html', create_default_context())


'''Open the Survey with the given survey_id.'''
def open_survey(request, survey_id):
    survey_bean = get_object_or_404(Survey, pk = survey_id)
    request_context = create_survey_context(survey_bean)
   
    if survey_bean.is_survey_owner(users.get_current_user().email()):
        return render(request, 'survey/owner_detail.html', request_context)
    return render(request, 'survey/user_detail.html', request_context)

    
'''Show the results for the Survey with the given survey_id.'''
def show_results(request, survey_id):
    survey_bean = get_object_or_404(Survey, pk = survey_id)
    return render(request, 'survey/results.html', create_survey_context(survey_bean))


'''Use AppEngine-provided functionality to log the user out.'''
def logout(request):
    return redirect(users.create_logout_url('/'))


'''Create a Survey with the user-specified title.'''
def create_survey(request):
    user_email = users.get_current_user().email()

    if request.method != 'POST' or not ProfileForm().exists_profile(user_email):
        raise Http404
   
    survey_form = SurveyForm(request.POST)
    if not survey_form.is_valid():
        context = create_default_context()
        context['survey_form'] = survey_form  #To display form errors on the home page
        return render(request, 'survey/home.html', context)
 
    user_bean = UserProfile.objects.get(email = user_email)
    survey_bean = survey_form.save(commit = False) #Convert the form into a bean.
    survey_bean.owner = user_bean #Set the bean's owner.
    survey_bean.save() #Save the bean in the database.
    return redirect('/survey/' + str(survey_bean.id) + '/')


'''Delete the Survey with the given survey_id.'''
def delete_survey(request, survey_id):
    if request.method != 'POST':
        raise Http404
    
    survey_bean = get_object_or_404(Survey, pk = survey_id)
    # Make sure that the deletion request came from the Survey owner. If not, display an error message.
    if not survey_bean.is_survey_owner(users.get_current_user().email()):
        context = create_default_context()
        context['privileges_error'] = 'This survey can be deleted only by its creator.'
        return render(request, 'survey/home.html', context) 
    
    survey_bean.delete() # Delete the Survey.
    return redirect('/survey/') #Redirect to prevent multiple survey creations via F5.


'''Change the title of the Survey with the given survey_id.'''
def edit_title(request, survey_id):
    survey_bean = get_object_or_404(Survey, pk = survey_id)
    
    # If we did not receive a POST request or the current user is not the
    # Survey's owner, then do not allow the user to change the Survey's title.
    if request.method != 'POST' or not survey_bean.is_survey_owner(users.get_current_user().email()):
        raise Http404
    
    survey_form = SurveyForm(request.POST)
    if survey_form.is_valid():
        survey_bean.survey_title = survey_form.cleaned_data['survey_title']
        survey_bean.save() 
    return redirect('/survey/' + survey_id + '/')
    

'''Create a Question in the Survey with the given survey_id.'''
def create_question(request, survey_id):
    survey_bean = get_object_or_404(Survey, pk = survey_id)
    if request.method != 'POST' or not survey_bean.is_survey_owner(users.get_current_user().email()):
        raise Http404
    # request.FILES and request.POST are both dicts; QuestionForm will use these
    # arguments to set its fields to user inputs.
    # request.FILES -> for image uploads
    question_form = QuestionForm(request.POST, request.FILES)
    # Each response field had the same name - response_text - so we can access the
    # whole list of responses in the following manner.
    response_list = request.POST.getlist('response_text')
    response_form = ResponseForm()  # Will be used to validate & save Responses
   
    if not question_form.is_valid():
        context = create_survey_context(survey_bean)
        context['question_form'] = question_form  #To show form errors
        return render(request, 'survey/owner_detail.html', context)
   
    if not response_form.is_valid_response_list(response_list):  #Insufficient responses
        context = create_survey_context(survey_bean)
        context['response_error'] = 'Please specify at least 2 response options.'
        return render(request, 'survey/detail.html', context)
   
    question_bean = question_form.save(commit=False)  #Convert the form into a bean.
    question_bean.survey = survey_bean #Set the Foreign Key.
    if request.FILES:
        question_bean.image_file = request.FILES['file']
    question_bean.save()
    response_form.save_response_list(question_bean, response_list)
    
    return redirect('/survey/' + survey_id + '/')


'''Submit responses for the Survey with the given survey_id.'''
def submit_survey(request, survey_id):
    if request.method != 'POST':
        raise Http404
    
    survey_bean = get_object_or_404(Survey, pk = survey_id)

    for response_id in request.POST.values():
        response_bean = get_object_or_404(Response, pk = response_id)
        if not survey_bean.contains_response(response_bean):
            break
        response_bean.increment_votes()
        response_bean.save()

    return redirect('/survey/' + survey_id + '/')   


'''Show the image with the given question_id in the Survey 
   with the given survey_id.'''
def show_image(request, survey_id, question_id):
    question_bean = get_object_or_404(Question, pk = question_id)
    image = question_bean.image_file
    
    if not image:
        return redirect('/survey/' + survey_id)
    
    response = HttpResponse(image)
    response['Content-Type'] = guess_type(image.file.name)
    return response

django-survey/survey/templates/survey/home.html
{% extends "base.html" %}

{% block pageTitle %} Home {% endblock %}
{% block pageHeading %} Welcome, {{ user_email }}! {% endblock %}

{% block globalMessage %}
 {% if privileges_error %}
  <div class="span6 offset4">
    <div class="alert alert-info"> {{ privileges_error }} </div>
  </div>
 {% endif %}
{% endblock %}

{% block displayBlock %}
 <div class="row">
  <div class="span8 offset4">
   <table class="table table-condensed table-hover"> 
    {% if survey_list %}
     <thead>
      <tr>
       <th />
       <th> Survey Title </th>
       <th> Survey Creator </th>
       <th> Date Created </th>
      </tr>
     </thead>
   
     {% for survey in survey_list %}
      <tr> 
       <td>
        <form action="{% url 'survey:delete_survey' survey.id %} " method="POST"> 
          {% csrf_token %}
          <input type="submit" class="btn btn-mini btn-danger" value="&times;" />
        </form>
       </td>
       <td> <a href="{% url 'survey:open_survey' survey.id %}"> {{ survey.survey_title }} </a> </td>
       <td> {{ survey.owner.email }} </td>
       <td> {{ survey.date_created }} </td>
       <td> <a href="{% url 'survey:show_results' survey.id %}"> See Results </a> </td>
      </tr> 
     {% endfor %}
    {% endif %}
   </table>
  </div>
 </div>
{% endblock %}

<!-- Form to create new surveys. -->
{% block creationBlock %}
 <div class="row">
  <div class="span6 offset4">
   <form action="{% url 'survey:create_survey' %}" method="POST">
     {% csrf_token %}      
     <label> Survey Title: </label> 
     <div class="input-append">
       <input type="text" id="appendedInputButton" name="survey_title" 
              maxlength="200" placeholder="Enter A Survey Title" />
       <input type="submit" class="btn btn-primary" value="Create Survey" /><br/>
     </div>
     <div class="errorMessages"> {{ survey_form.survey_title.errors|striptags}} </div>
   </form>
  </div>
 </div>
{% endblock %}

django-survey/survey/templates/survey/owner_detail.html
{% extends "base.html" %}

{% block pageTitle %} {{ survey.survey_title }} {% endblock %}
{% block navbar %}
  <li><a href="{% url 'survey:show_results' survey.id %}"> Survey Results </a></li> 
{% endblock %}
{% block headingClass %} contenteditable="true" onblur="editTitle(this, {{ survey.id }});" {% endblock %}
{% block pageHeading %} {{ survey.survey_title }} {% endblock %}

{% block globalMessage %}
 {% if response_error %}
  <div class = "span6 offset4">
   <div class="alert alert-error">
     <strong> {{ response_error }} </strong>  
   </div>
  </div>
 {% endif %}
{% endblock %}

{% block displayBlock %}
 {% load survey_extras %}
 <div class="row-fluid">
  {% block displayLayout %}<div class="span6">{% endblock %}
   <div class="hero-unit">
    {% if survey.question_set.all %}
     <form action="{% url 'survey:submit_survey' survey.id %}" method="POST">
      <ol>
       {% for question in survey.question_set.all %}
        <li> {{ question.question_text }} </li>
        {% if question.image_file %}
          <img src="{% url 'survey:show_image' survey.id question.id %}" /> <br/>
        {% endif %}
        {% for response in question.response_set.all|order_by:"position" %}
          <input type="radio" name={{question.id}} value={{response.id}} />
          {{ response.response_text }} <br/>
        {% endfor %}
        <br/>
       {% endfor %}
       <input type="submit" class="btn btn-success" value="Submit Survey" />
       <input type="reset" class="btn btn-danger" value="Clear Survey" />
      </ol>
     </form>
    {% endif %}
   </div>
  </div>
{% endblock %}

{% block creationBlock %}
 <div class="span6"> 
  <div class="hero-unit">
   <form action="{% url 'survey:create_question' survey.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label> Enter a question: </label> 
    <input type="text" name="question_text" maxlength="200" />
    <div class="errorMessages"> {{ question_form.question_text.errors|striptags }} </div>
    <input type="file" name="file" /> <br/><br/>
    <ul id="response_options">
      <li> <input type="text" name="response_text" maxlength="200"/> </li>
      <li> <input type="text" name="response_text" maxlength="200"/> </li>
    </ul>
    <button class="btn btn-info" onclick="addChoice(); return false;"> Add Response Option </button>
    <button class="btn btn-info" onclick="removeChoice(); return false;"> Remove Response Option </button>
    <input type="submit" class="btn btn-primary" value="Create Question"/>
   </form>
  </div>  
 </div>
</div>
{% endblock %}

django-survey/survey/templates/survey/results.html
{% extends "base.html" %}

{% block pageTitle %} Results {% endblock %} 
{% block navbar %} 
  <li><a href="{% url 'survey:open_survey' survey.id %}"> Return to Survey </a></li> 
{% endblock %}
{% block pageHeading %} Results for {{ survey.survey_title }} {% endblock %}

{% block displayBlock %}
 {% for question in survey.question_set.all %}
  <div class="featurette">
   <h2 class="featurette-heading"> {{ question.question_text }} </h2>
   <div class="row">
    <div class="span4 offset3">
      <table class="table table-condensed table-bordered table-hover">
       <thead>
        <tr>
         <th> Response Option </th>
         <th> Number of Votes </th>
        </tr>
       </thead>
   
       <tbody>
        {% load survey_extras %}
        {% for response in question.response_set.all|order_by:"position" %}
         <tr>
           <td> {{ response.response_text }} </td>
           <td> {{ response.votes }}  </td>
         </tr>
        {% endfor %}
       </tbody>
      </table>
    </div>
   </div>
  </div>
 {% endfor %}
{% endblock %}

django-survey/survey/templates/survey/user_detail.html
{% extends "survey/owner_detail.html" %}

{% block headingClass %} {% endblock %}
{% block creationBlock %} {% endblock %}
{% block displayLayout %}<div class="span6 offset4">{% endblock %}